### ISSUE TITLE
Bad id_token issuer

### ISSUE THREAD

**Issue by callmekatootie** [TimothyJones/github-cognito-openid-wrapper#100]
I am using the lambda based deployment, and in Cognito, I had to manually provide the OpenID endpoints.

One of the endpoints to provide is the issuer URL. Here, the [documentation](https://github.com/TimothyJones/github-cognito-openid-wrapper#3-finalise-cognito-configuration) states:

```
Issuer: https://<Your API Gateway DNS name>/${Stage_Name} or https://<your webserver>/ (for the node server).
```

However, I would get an error at the end of the Oauth flow:

```
Bad id_token issuer https://<Your API Gateway DNS name>
```

It seems that for the issuer URL, the endpoint to specify is:

```
https://<Your API Gateway DNS name>
```

There's no Stage_name to be provided here.

And that seemed to do the trick.

**Comment by TimothyJones** [comment]
Ah! Thanks for the report, I’ll correct this

**Comment by callmekatootie** [comment]
No, sorry - hold on. I am still facing issues. Haven't gotten to the bottom of it yet.

**Comment by callmekatootie** [comment]
The cause of the issue seemed to be a custom code that we have, which did not correctly append the stage to the issuer (for when cognito will query the `/.well-known/openid-configuration` endpoint.

The current documentation is correct - no changes needed. Apologies for the trouble.
