### ISSUE TITLE
Add Passing Request Parameters as JWT

### ISSUE THREAD

**Issue by blakehatch** [TimothyJones/github-cognito-openid-wrapper#124]
Add support for connect core feature missing from shim ([spec](https://openid.net/specs/openid-connect-core-1_0.html#JWTRequests)).

**Comment by TimothyJones** [comment]
Thanks for the report! Could you elaborate a bit about why this is useful? I had quick skim and it looks like it’s optional?

The intention was to implement the parts that cognito needs, but I’d be open to accepting PRs extending the interface if it’s useful.
