### ISSUE TITLE
When integrating with Okta, for testing purposes this fails. 

### ISSUE THREAD

**Issue by sanjeevbadwal3** [TimothyJones/github-cognito-openid-wrapper#130]
I am setting this up with Okta but it fails, can I maybe setup a meeting show a replication setup?

**Comment by TimothyJones** [comment]
Could you perhaps describe your issue first? It might not need a call to sort it out

**Comment by TimothyJones** [comment]
Without further details, I'm not sure I can help. Feel free to reopen with more information if this is still a problem
