### ISSUE TITLE
Autodiscovery issue

### ISSUE THREAD

**Issue by clapas** [TimothyJones/github-cognito-openid-wrapper#14]
I fixed the issue with the autodiscovery by moving the `jwks.json` endpoint into the `/.well-known` path, similar to the OpenIdDiscovery endpoint.

**Comment by TimothyJones** [comment]
Aha! Thank you! Odd that it wouldn't pick it up from the discovery endpoint.

I'll fix this next time I have a free moment - unless you're able to make a PR?
