### ISSUE TITLE
Bit uncomprehensive setup instructions

### ISSUE THREAD

**Issue by lolejar** [TimothyJones/github-cognito-openid-wrapper#23]
Hello,

first I must admit I am not node developer and I am just following setup instructions in the README. I've setup user Pool, GitHub application and update config.sh. I am trying to deploy this project via API Gateway and Lambda. First thing that strikes me is that it is not mentioned in section 2a to source config.sh like in 2b. Is it not necessary ? Either way I still end up when running npm run deploy with following errors. Either as it is said that it is not a problem with npm I can't find out what I am doing wrong. 

OS : OS X
aws-cli/1.16.212 Python/3.7.5 Darwin/18.7.0 botocore/1.12.204
SAM CLI, version 0.35.0
NPM 6.12.1

----------------|----------|----------|----------|----------|-------------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------|----------|----------|----------|----------|-------------------|
All files       |    83.91 |    30.77 |    86.96 |    83.33 |                   |
 src            |     85.9 |    43.75 |    86.96 |    85.33 |                   |
  config.js     |      100 |      100 |      100 |      100 |                   |
  crypto.js     |    66.67 |      100 |        0 |    66.67 |       11,18,23,24 |
  github.js     |    70.83 |       25 |     87.5 |    70.83 |... 24,25,30,31,34 |
  helpers.js    |      100 |      100 |      100 |      100 |                   |
  openid.js     |      100 |      100 |      100 |      100 |                   |
 src/connectors |    66.67 |       10 |      100 |    66.67 |                   |
  logger.js     |    66.67 |       10 |      100 |    66.67 |          16,18,27 |
----------------|----------|----------|----------|----------|-------------------|

Test Suites: 1 failed, 2 passed, 3 total
Tests:       10 failed, 10 passed, 20 total
Snapshots:   0 total
Time:        1.763s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! github-cognito-openid-wrapper@1.1.0 test: `jest --runInBand --coverage`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the github-cognito-openid-wrapper@1.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lolejar/.npm/_logs/2019-12-04T09_36_00_880Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! github-cognito-openid-wrapper@1.1.0 prebuild-dist: `npm run lint && npm run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the github-cognito-openid-wrapper@1.1.0 prebuild-dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lolejar/.npm/_logs/2019-12-04T09_36_00_898Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! github-cognito-openid-wrapper@1.1.0 predeploy: `npm run build-dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the github-cognito-openid-wrapper@1.1.0 predeploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lolejar/.npm/_logs/2019-12-04T09_36_00_916Z-debug.log

**Comment by lolejar** [comment]
Further debug logs show following

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'test' ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle github-cognito-openid-wrapper@1.1.0~pretest: github-cognito-openid-wrapper@1.1.0
6 info lifecycle github-cognito-openid-wrapper@1.1.0~test: github-cognito-openid-wrapper@1.1.0
7 verbose lifecycle github-cognito-openid-wrapper@1.1.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle github-cognito-openid-wrapper@1.1.0~test: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/lolejar/Work/Cognito/github-cognito-openid-wrapper/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/lolejar/Work/Cognito/github-cognito-openid-wrapper/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/lolejar/Work/Cognito/github-cognito-openid-wrapper/node_modules/.bin:/Users/lolejar/.pyenv/shims:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle github-cognito-openid-wrapper@1.1.0~test: CWD: /Users/lolejar/Work/Cognito/github-cognito-openid-wrapper
10 silly lifecycle github-cognito-openid-wrapper@1.1.0~test: Args: [ '-c', 'jest --runInBand --coverage' ]
11 silly lifecycle github-cognito-openid-wrapper@1.1.0~test: Returned: code: 1  signal: null
12 info lifecycle github-cognito-openid-wrapper@1.1.0~test: Failed to exec test script
13 verbose stack Error: github-cognito-openid-wrapper@1.1.0 test: `jest --runInBand --coverage`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid github-cognito-openid-wrapper@1.1.0
15 verbose cwd /Users/lolejar/Work/Cognito/github-cognito-openid-wrapper
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error github-cognito-openid-wrapper@1.1.0 test: `jest --runInBand --coverage`
22 error Exit status 1
23 error Failed at the github-cognito-openid-wrapper@1.1.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by TimothyJones** [comment]
Those are some strange looking errors. Have you done

npm install

First?

**Comment by lolejar** [comment]
of course I did, the npm install first time
- it created keys
- dtrace_provider complained about some errors
   (TypeError: '>=' not supported between instances of 'tuple' and 'str')
- got 5 vulnerabilities (found 5 vulnerabilities (1 low, 1 moderate, 3 high))

first time i've run it i've got errors about 2 dependencies that weren't able to be installed and required manual install (acorn@ˆ6.0.0 and ajv@^6.0.0) which i've installed 

npm install acorn@^6.0.0
npm install ajv@^6.0.0

and now when i try to run npm run deploy -> github.pact.test.js test are failing and producing those errors above

errors are like

 ● GitHub Client Pact › UserDetails endpoint › When the access token is good › returns a sucessful body
    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
● GitHub Client Pact › UserDetails endpoint › When the access token is good › returns a sucessful body
    connect ECONNREFUSED 127.0.0.1:8989
  ● GitHub Client Pact › UserDetails endpoint › When the access token is good › returns a sucessful body
    TypeError: Cannot read property 'addInteraction' of undefined

**Comment by TimothyJones** [comment]
Thanks for the extra detail, that's very helpful. I'm trying to reproduce this now and I'll report back shortly.

You asked about `source config.sh` - it's not necessary in step 2a, which is why the instruction is missing. I might add a note to the readme to avoid confusion in the future.

Are there other areas where you found the setup instructions uncomprehensive?

**Comment by TimothyJones** [comment]
Unfortunately, I'm unable to reproduce this locally. 

Given the errors, I suspect the pact test is failing to wait for the server to start, so I've increased the test timeouts for those tests. I also upgraded the versions of a few dependencies.

Try pulling the latest version, then `npm install` followed by `npm test`

**Comment by TimothyJones** [comment]
If you're still having trouble, I'd be interested in the error you're having with `node-gyp`.

The acorn and ajv-keywords peer-dependency warnings you can ignore - you don't need to install those packages (but it won't hurt if you did). I'll see if I can remove them with careful pruning of dependencies, but it's usually not possible.

**Comment by lolejar** [comment]
Thank you very much it is working now. I have one questioned related though if you don't mind. I've attached Cognito configured user pool to AWS ALB. Everything works as far as I am logged in to GitHub before I attempt to login via ALB. I go to ALB I get Authorization / Login page and I am able to authenticate via OAuth app. But when I am not logged in github in another window (session) I get 500 (Looks like something went wrong!) page instead of Authorization / Login page.

**Comment by TimothyJones** [comment]
So, there's an issue with GitHub where it rejects the `state` sent by Cognito when 2FA is enabled and the user is not logged in. We did a fair bit of testing and couldn't figure out exactly what the issue was - but we think it is to do with the length of the `state` parameter provided by Cognito.

You can work around this by generating your own (shorter) `state` token and sending them on to GitHub - but if you do this, the shim needs to maintain state, and there's an extra step where GitHub redirects back to the shim, which redirects back to Cognito. 

A colleague has a private fork of this repo which maintains a mapping of the Cognito states, using a dynamo DB table to do this. I'd like to look at merging it in, but I'm in two minds, because it's adding a fair bit of extra resources (and therefore impacts cost and scalability) in order to work around a GitHub bug. What do you think?

**Comment by lolejar** [comment]
Thank you for reply. I answered to separate issue thread.
