### ISSUE TITLE
Cognito giving us error back invalid response token

### ISSUE THREAD

**Issue by SSKasture** [TimothyJones/github-cognito-openid-wrapper#3]
Hi @TimothyJones ,

This is question ,it's not error related to this shim,just want to know if you have some insight about it.

When our OAuth  application return code back to Cognito , oauth2/idpresponse end point.
We are getting error 
``` http://localhost:8080/?error_description=Bad+token+response%3A+HTTP%2F1.1+400+Bad+Request%2C+entity%3A+Failure%3A+%27Request+failed+with+status+code+400%27&error=invalid_request```

Let me know if have any idea about this.
Thank You
Sampada K.

**Comment by TimothyJones** [comment]
I'm afraid I'm not sure. I would check with the cognito [documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-userpools-server-contract-reference.html) to make sure that you're sending the correct parameters to the correct endpoint.

**Comment by Linus-Boehm** [comment]
@SSKasture Did you found a solution/reason for that?

**Comment by TimothyJones** [comment]
You can also hit this if the flow you are requesting isn’t enabled in the cognito app client

**Comment by Linus-Boehm** [comment]
I am using it on localhost with ngrok . The error seams to come from the POST /token endpoint
but cant see anything wrong
Error: `Failure: 'connect ECONNREFUSED 127.0.0.1:80'`
Payload:
```
client_id: <Github Client ID>
client_secret: <Github Secret>
grant_type: authorization_code
redirect_uri: https://<my domain>.auth.eu-central-1.amazoncognito.com/oauth2/idpresponse
```

**Comment by busla** [comment]
> I am using it on localhost with ngrok . The error seams to come from the POST /token endpoint
> but cant see anything wrong
> Error: `Failure: 'connect ECONNREFUSED 127.0.0.1:80'`
> Payload:
> 
> ```
> client_id: <Github Client ID>
> client_secret: <Github Secret>
> grant_type: authorization_code
> redirect_uri: https://<my domain>.auth.eu-central-1.amazoncognito.com/oauth2/idpresponse
> ```
> 
> Can u see an obvious error? I don't even get why or where its calling localhost on port 80
> EDIT: Found it, just an issue locally

Could you share your fix?

**Comment by sambhavjain9138** [comment]
```
const getApiEndpoints = (
  apiBaseUrl = "https://api.github.com",
  loginBaseUrl = "https://github.com"
) => ({
  userDetails: `${apiBaseUrl}/user`,
  userEmails: `${apiBaseUrl}/user/emails`,
  oauthToken: `${loginBaseUrl}/login/oauth/access_token`,
  oauthAuthorize: `${loginBaseUrl}/login/oauth/authorize`
});
```

@busla Can you replace the function in src/github.js, line 11 function with the above one? I ran into the same issue and found that these 2 parameters were undefined for me as I haven't specified it in my config.sh file because it was commented as not required. Let me know if this works for you
