### ISSUE TITLE
Can I use the access token to access the GitHub API?

### ISSUE THREAD

**Issue by akserg** [TimothyJones/github-cognito-openid-wrapper#31]
Hi @TimothyJones, thank you for share your code.

I successfully installed shim on my AWS account and I can log in to my application through registered GitHub App. My question is that - how can I get access to GitHub API, for example, to get a list of repositories or make a commit? I tried to use the access token and id token from Cognito User without luck.

I'm using `aws-amplify` library for login with hosted UI:

```
import { Auth, Hub } from 'aws-amplify';
import { CognitoUser } from '@aws-amplify/auth';
const axios = require('axios');
//...

Hub.listen('auth', async ({ payload: { event, data } }) => {
    switch (event) {
        case 'cognitoHostedUI':
            this.successAuth();
            const cognitoUser: CognitoUser = await Auth.currentAuthenticatedUser();
            const session = await Auth.currentSession();
            const token = session.getIdToken();
            let axios_req = {
                method: 'get',
                url: 'https://api.github.com/user',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                    'Authorization': `token ${token}`
                }
            };
            axios(axios_req).then(res => {
                console.log('SUCCESS:', res);
                return res;
            }, err => {
                console.log('ERROR:', err);
            });
            break;
    }
});
```

The response always `401 Unauthorized`:
```
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
```

Thank you in advance,
Sergey.

**Comment by TimothyJones** [comment]
This wrapper is for providing federated logins to Cogntio. With federated logins, the login method will be abstracted from your application, so you'll only see Cognito tokens (which won't be able to be used to access github). 

However, if you really want to provide access to Github, I think you could put the github access token on the Cognito user object in cognito as a custom claim. Of course, if your User Pool has other ways of signing in to it, the github token won't be available to those users.

**Comment by akserg** [comment]
Thank you for the prompt answer.

**Comment by safaiyeh** [comment]
hey @akserg how did you solve this problem? I also use Amplify
