### ISSUE TITLE
Getting username attribute mapping required error

### ISSUE THREAD

**Issue by vradars234** [TimothyJones/github-cognito-openid-wrapper#37]
I took a pull of the workaround-2fa-bug branch and ended up resolving the invalid state issue that i was facing by storing the state mapping in a dynamodb table. But after we send the state and authenticate code to cognito hosted domain I get the username attribute mapping required error even though I have already configured that in the attribute mapping section.

**Comment by kujtimiihoxha** [comment]
@vradars234 what resolved the invalid state issue? I am facing the same issue also

**Comment by TimothyJones** [comment]
See #24 for discussion of the invalid state issue.

I’m unable to reproduce the attribute mapping error- have you double checked the rest of the setup instructions? Can you confirm the exact error that you are getting?

**Comment by TimothyJones** [comment]
I'm assuming this got resolved - please feel free to reopen if that is not the case.
