### ISSUE TITLE
GitHub Error - 400 error getting token

### ISSUE THREAD

**Issue by mariusmitrofan** [TimothyJones/github-cognito-openid-wrapper#39]
:( 

...

I'm hoping it's just a reconfiguration problem, but it doesn't look as so.

Apparently, the call to GitHub gets successfully executed, the actual login to GitHub is successful, but when the callback gets, done it seems, it fails miserably with the error in the title -> "GitHub Error - 400 error getting token" from Cognito.

I've compared the response from a provider that works (Google) and this one (GitHub), and noticed that the `/oauth2/idpresponse` URL differs a bit.

Specifically, Google exports these parameters in the URL: code,state,scope,authuser,prompt
While, GitHub only exports: code,state

I don't know if it's relevant or not, but this is the only thing I could find.

Do you guys have any clues or any ideas in which directions to look at?

PS: The wrapper was deployed with ApiGateway/Lambda logic.

**Comment by mariusmitrofan** [comment]
@TimothyJones do you think you could help me on this ?

 I can't seem to find any step that I did wrong...

**Comment by mariusmitrofan** [comment]
I'm a moron :+1: 

Plugin works.

Please disregard...

**Comment by TimothyJones** [comment]
Haha! We’ve all been there. Glad you got it working.

Is there anything I should make clearer in the documentation?
