### ISSUE TITLE
sam deploy missing RegionParameter 

### ISSUE THREAD

**Issue by DALDEI** [TimothyJones/github-cognito-openid-wrapper#4]
running npm run deploy, there is an error when running sam deploy.
There needs be an additional parameter overide  RegionParameter=$REGION,  or a default set in the template.

Manually running the failed command with the region argument appears to work
(not tested yet, but the stack did run)

`sam deploy --region us-west-2 --template-file /moji/github-cognito-openid-wrapper/scripts/../serverless-output.yml --stack-name xxxx --parameter-overrides GitHubClientIdParameter=xxx GitHubClientSecretParameter=xxxx  CognitoRedirectUriParameter=xxxx  RegionParameter=$REGION --capabilities CAPABILITY_IAM`

**Comment by TimothyJones** [comment]
Ah, whoops. I have a default region set in my AWS config, which might be why it worked on mine. Thanks for the report!

**Comment by TimothyJones** [comment]
I see the region parameter there in the deploy script:

https://github.com/TimothyJones/github-cognito-openid-wrapper/blob/master/scripts/deploy.sh#L24

Am I missing somewhere else that I've missed the parameter?

**Comment by TimothyJones** [comment]
Closing because I think this is fixed, but please feel free to reopen if I missed something.
