### ISSUE TITLE
Will I be able to consume the GitHub access_token?

### ISSUE THREAD

**Issue by safaiyeh** [TimothyJones/github-cognito-openid-wrapper#40]
I will need the GitHub access_token for my app, how can I access that if possible?

https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#2-users-are-redirected-back-to-your-site-by-github

**Comment by TimothyJones** [comment]
This wrapper doesn’t provide it because it doesn’t necessarily make sense. My advice would be to consume github oauth directly if you need this.

However, if for some reason you need to use cognito, you can find a short discussion on #31 that may help.

**Comment by safaiyeh** [comment]
Thanks! I’ll try that out.

**Comment by TimothyJones** [comment]
You’re welcome.

You’re not the first to ask about this, so it might make sense to add a pass-through for the token as an optional feature (even though it doesn’t make sense for most use cases, it would still be nice to enable it where possible).

**Comment by safaiyeh** [comment]
Hey @TimothyJones following up on this!

I added the access_token as a custom attribute it seems like my Cognito User object doesn't return it.
![Screen Shot 2020-11-04 at 9 36 17 PM](https://user-images.githubusercontent.com/8675043/98201989-d08a4a00-1ee5-11eb-9a4b-2f101b04fc46.png)

![Screen Shot 2020-11-04 at 9 37 20 PM](https://user-images.githubusercontent.com/8675043/98202045-ee57af00-1ee5-11eb-89ad-c079d5251b63.png)

**Comment by safaiyeh** [comment]
Actually, I didn't give it time to propagate. It shows up now
