### ISSUE TITLE
Way to add GitHub OAuth scopes

### ISSUE THREAD

**Issue by shufflemattdev** [TimothyJones/github-cognito-openid-wrapper#42]
Hi there thank you for this great wrapper! I am using a custom attribute to capture the GitHub access token, and I was wondering if there was a way to specify additional GitHub [OAuth Scopes](https://docs.github.com/en/free-pro-team@latest/developers/apps/scopes-for-oauth-apps)? The wrapper is currently requesting limited scopes to gather basic info like email, but in my case I need a bit more, is there any way to specify additional GitHub specific scopes like repo etc?

**Comment by TimothyJones** [comment]
Yes, this wrapper passes on any scopes it gets from Cognito. So, in the [finalise cognito configuration](https://github.com/TimothyJones/github-cognito-openid-wrapper#3-finalise-cognito-configuration) setup step, you can add scopes there.

Note that if you want to do anything with those scopes, it would have to be a code change. You would have to implement the client for anything extra in [the github module](https://github.com/TimothyJones/github-cognito-openid-wrapper/blob/master/src/github.js), and then use that call in the [userinfo's Promise array](https://github.com/TimothyJones/github-cognito-openid-wrapper/blob/master/src/openid.js#L9) in the openID layer.

**Comment by shufflemattdev** [comment]
Got it @TimothyJones got it thank you sir! Closing this

**Comment by adam-nygate** [comment]
@TimothyJones do you know of any way to have scopes defined in a _passthrough_ manner?

My use case is that I'd like my app to have certain scopes during the initial registration, but on a certain event (user-initiated), we'd re-authorise them with the additional scopes?
