### ISSUE TITLE
GitHub App vs Github OAuth App

### ISSUE THREAD

**Issue by smohiuddin** [TimothyJones/github-cognito-openid-wrapper#45]
Will this wrapper still work with the newer Github App vs the Github OAuth App

https://docs.github.com/en/developers/apps/differences-between-github-apps-and-oauth-apps

**Comment by TimothyJones** [comment]
No, this is a wrapper for GitHub’s OAuth, so the other style of GitHub apps won’t work to back it. I’m not sure what that would look like?

**Comment by TimothyJones** [comment]
I'm going to close this for now. Please feel free to reopen with more details if this is something you need.
