### ISSUE TITLE
deploy fails if bucket exists

### ISSUE THREAD

**Issue by DALDEI** [TimothyJones/github-cognito-openid-wrapper#5]
If the bucket in config.sh already exists (either first time or during a update/redeploy) then deploy fails.
This is fixed by adding "|| true"  to the end of the "aws s3 mb" commande 

I may get around to fixing both this and #4 and submit  a PR, 
And by the way THANK YOU -- !~ THIS IS AWESOME IN SO MANY WAYS

**Comment by TimothyJones** [comment]
Ah, nice catch. Thanks for the report!

A PR would be very welcome, if you have the time.

I’m glad the project is useful - thanks for the appreciation!

**Comment by TimothyJones** [comment]
Fixed by #6. Thanks again!
