### ISSUE TITLE
Using cognito /logout endpoint not initiating new authn handshake with GitHub

### ISSUE THREAD

**Issue by bensullivan** [TimothyJones/github-cognito-openid-wrapper#51]
Hi Timothy,

So the token integration is working well for us 🥳  with the authorize endpoint.

I'm now testing the clearing of the session via the /logout Cognito endpoint.  My scenario is as follows:

1.  Logout of GitHub
2.  Call the /logout Cognito endpoint
3.  Call the /oauth/authorize Cognito endpoint

My expectation is that I should be presented with the GitHub authentication screen but I am getting the access and id tokens back again without authentication.

I have spoken to AWS and screen shared with them.  Their suggestion was to speak with you.  Is it possible the shim is caching the id token and returning it instead of initiating the sign in flow with GitHub?  Clutching at straws...

I can talk to our CTO about some airpairing if you're available and OK with signing an NDA?  Where are you based?

Thanks again for your help

Ben

**Comment by bensullivan** [comment]
Interestingly, when the /oauth/authorize endpoint is called again in step three, although it's not triggering a new auth flow to GitHub, it is sending a new access and id token (ie different to the ones sent in the prior call to authorize before step 1).

So Cognito is starting a new session but for some reason not initiating the GitHub auth...

**Comment by TimothyJones** [comment]
Yes, that’s right. This is exactly the situation I described on the other issue you raised.

When the user tries to log in to cognito, cognito defers them to GitHub.

If they are already logged in on GitHub, GitHub immediately returns a successful session to Cognito.

Only when they are not logged in on GitHub or have not yet authorized your application will they see the GitHub login page. This behaviour is up to GitHub, and is not part of your application, cognito, or the shim. 

If you check the logs, you should see the authorise flow being triggered correctly.

**Comment by TimothyJones** [comment]
How did you go with this one? I’ll close for now, feel free to reopen if there is a problem

(I’m based in Melbourne, Australia)

**Comment by bensullivan** [comment]
Hi yeah I solved it - turns out cognito session cookie doesn't work as expected if window.location.href used so I switched to putting the link in the html button.  Thanks again for your help!

**Comment by TimothyJones** [comment]
Oh right! I've never tried it that way - always used the link. Glad it
works!
