### ISSUE TITLE
Undefined GITHUB_API_URL and  GITHUB_LOGIN_URL

### ISSUE THREAD

**Issue by sambhavjain9138** [TimothyJones/github-cognito-openid-wrapper#63]
Hii Team
I have used this package to configure github with Cognito. I have deployed the package in my local and have publically exposed it using Ngrok.
In the src/github.js file, the following 2 parameters are not defined in the config.sh file (Because a comment, in the config.sh file, states that it is only required for github enterprises). Can you please help with the place where these parameters are required to be defined because I have currently hard coded these 2 parameters as follow, on line no 12 and 13 of github.js file.
```
apiBaseUrl = "https://api.github.com"
loginBaseUrl = "https://github.com"
```

Can you please help me with the same?

**Comment by TimothyJones** [comment]
Thanks for this! I thought this was fixed already, but apparently not - now fixed by https://github.com/TimothyJones/github-cognito-openid-wrapper/commit/bb3ace5b87aa74200e226e72bfa21f59df90a8d0
