### ISSUE TITLE
End of AWS Lambda support for nodejs10: July 30th

### ISSUE THREAD

**Issue by mfogel** [TimothyJones/github-cognito-openid-wrapper#64]
Hi, thanks a bunch for putting this project together. Seriously.

You may already know, but AWS Lambda is [ending support for nodejs10 runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html). Full support ends July 30th, 2021.

My understanding is that after July 30th, 2021, new users of this project won't be able to deploy it because of the [`Runtime`](https://github.com/TimothyJones/github-cognito-openid-wrapper/blob/v1.2.0/template.yml#L9) setting.

**Comment by rryoung98** [comment]
although I'm running into similar issues to #65, i think just upgrading the node version works just fine.

**Comment by TimothyJones** [comment]
Fixed by #74
