### ISSUE TITLE
Question: Deployment with Serverless framework

### ISSUE THREAD

**Issue by tobilg** [TimothyJones/github-cognito-openid-wrapper#7]
Thanks for your work on the project. As a frequent Serverless framework user, I'd like to get your POV if an (additional) deployment method via Serverless would make sense. If yes, I think I could create a `serverless.yml` for this project within a PR.

**Comment by TimothyJones** [comment]
I think it would be great to have deployment scripts for Serverless. A PR would be very welcome! 

I haven’t used it much myself - would you be able to also expand the readme with Serverless deploy instructions?

**Comment by TimothyJones** [comment]
Hello! Did you get anywhere with this? No stress, just I might close the issue if there's no PR coming.

**Comment by tobilg** [comment]
@TimothyJones Sorry, this kind of skipped from my list of todos... Unfortunately, it looks like I won't have time to implement it soon. You can close the issue if you like.

**Comment by TimothyJones** [comment]
No stress. A PR would still be welcome if you change your mind, but no need if you're busy 👍
