### ISSUE TITLE
How can I limit GitHub authentication only for users in my GitHub organization 

### ISSUE THREAD

**Issue by azatsafin** [TimothyJones/github-cognito-openid-wrapper#83]
Hello, I would like to use GitHub user accounts and authenticate that user through Cognito. I have installed shim and it works so that GitHub users could authenticate via their GitHub accounts. I would like to limit users who can get authentication via GitHub by limiting them to my organization only. Is it possible? if so, could you please give advice on how to archive that?

**Comment by TimothyJones** [comment]
You can see some discussion on this topic here - https://github.com/TimothyJones/github-cognito-openid-wrapper/issues/26

I recommend you put the user's organisations into the userinfo response, and then read those in the app to determine whether they should have access. This means a user might be able to log in, federate into Cognito, but then not have access to your app.

**Comment by TimothyJones** [comment]
I'll close this for now - please feel free to reopen if you have further questions or the discussion on the other issue doesn't help.
